[0m22:50:53.685361 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105096150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105094fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1050ae290>]}


============================== 22:50:53.687109 | 117741af-ea06-44f3-ae75-0bc38114cbd0 ==============================
[0m22:50:53.687109 [info ] [MainThread]: Running with dbt=1.7.0
[0m22:50:53.687517 [debug] [MainThread]: running dbt with arguments {'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'indirect_selection': 'eager', 'introspect': 'True', 'target_path': 'None', 'use_experimental_parser': 'False', 'version_check': 'True', 'cache_selected_only': 'False', 'invocation_command': 'dbt run', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'send_anonymous_usage_stats': 'True', 'printer_width': '80', 'log_path': 'logs', 'no_print': 'None', 'static_parser': 'True', 'partial_parse': 'True', 'log_cache_events': 'False', 'profiles_dir': '/Users/tyrawls/.dbt', 'quiet': 'False', 'log_format': 'default', 'write_json': 'True', 'warn_error': 'None'}
[0m22:50:53.687933 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/tyrawls/Desktop/stock-data/new-horizons-financial/local-deploy/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:50:53.688772 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.036305543, "process_user_time": 0.802642, "process_kernel_time": 0.091557, "process_mem_max_rss": "108101632", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m22:50:53.689086 [debug] [MainThread]: Command `dbt run` failed at 22:50:53.689006 after 0.04 seconds
[0m22:50:53.689298 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1048e0950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10501d290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103a388d0>]}
[0m22:50:53.689499 [debug] [MainThread]: Flushing usage events
[0m22:51:06.072604 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111b1a8d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111b1be50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111b19fd0>]}


============================== 22:51:06.074113 | aea641d2-6c30-4a0b-9aac-69e6f946ff78 ==============================
[0m22:51:06.074113 [info ] [MainThread]: Running with dbt=1.7.0
[0m22:51:06.074505 [debug] [MainThread]: running dbt with arguments {'write_json': 'True', 'indirect_selection': 'eager', 'send_anonymous_usage_stats': 'True', 'quiet': 'False', 'version_check': 'True', 'introspect': 'True', 'no_print': 'None', 'log_format': 'default', 'target_path': 'None', 'printer_width': '80', 'debug': 'False', 'use_colors': 'True', 'profiles_dir': '/Users/tyrawls/.dbt', 'log_cache_events': 'False', 'static_parser': 'True', 'fail_fast': 'False', 'warn_error': 'None', 'partial_parse': 'True', 'log_path': 'logs', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt clean', 'use_experimental_parser': 'False', 'cache_selected_only': 'False'}
[0m22:51:06.075018 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/tyrawls/Desktop/stock-data/new-horizons-financial/local-deploy/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:51:06.075858 [debug] [MainThread]: Resource report: {"command_name": "clean", "command_wall_clock_time": 0.028788708, "process_user_time": 0.80049, "process_kernel_time": 0.091141, "process_mem_max_rss": "107659264", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m22:51:06.076163 [debug] [MainThread]: Command `dbt clean` failed at 22:51:06.076089 after 0.03 seconds
[0m22:51:06.076367 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111ac1250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1111a4d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107da60d0>]}
[0m22:51:06.076565 [debug] [MainThread]: Flushing usage events
[0m10:47:15.693143 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106063a10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10607a5d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106087f50>]}


============================== 10:47:15.695829 | 32f52e93-27a4-4542-b1b2-e132dc20130b ==============================
[0m10:47:15.695829 [info ] [MainThread]: Running with dbt=1.7.0
[0m10:47:15.696235 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'write_json': 'True', 'invocation_command': 'dbt run', 'cache_selected_only': 'False', 'introspect': 'True', 'log_cache_events': 'False', 'debug': 'False', 'no_print': 'None', 'version_check': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'quiet': 'False', 'warn_error': 'None', 'profiles_dir': '/Users/tyrawls/.dbt', 'target_path': 'None', 'partial_parse': 'True', 'use_experimental_parser': 'False', 'send_anonymous_usage_stats': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'log_format': 'default', 'static_parser': 'True', 'indirect_selection': 'eager', 'log_path': 'logs'}
[0m10:47:15.696582 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/tyrawls/Desktop/portfolio-optimization-project/local-storage/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:47:15.697587 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.032257374, "process_user_time": 0.835297, "process_kernel_time": 0.129438, "process_mem_max_rss": "118161408", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m10:47:15.697913 [debug] [MainThread]: Command `dbt run` failed at 10:47:15.697828 after 0.03 seconds
[0m10:47:15.698146 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105bb8950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1060a77d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1060a7b10>]}
[0m10:47:15.698356 [debug] [MainThread]: Flushing usage events
